### ISSUE TITLE
Importing GPX file not importing as expected

### ISSUE THREAD

**Issue by malsharman** [waypoint-guru/waypoint-guru-issues#4]
Uploaded a GPX file (Basecamp created but originally started in WPG) 

File imported as shown in screenshot
<img width="1436" alt="Screen Shot 2023-07-08 at 6 42 28 pm" src="https://github.com/waypoint-guru/waypoint-guru-issues/assets/2616721/bc7f64eb-e58a-441c-b668-cf573730d1e8">

Since GitHub doesn't allow uploading gpa file - have linked via dropbox
https://www.dropbox.com/s/em2srghthqo22qc/Bunya%20Moutains%20Loop-Revised.GPX?dl=0

**Comment by TimBarham** [comment]
There's a workaround in the beta, by gracefully handling routes with more waypoints that Google Maps API can handle. Upcoming release also relaxes the waypoint limit.
